apiVersion: batch/v1
kind: CronJob
metadata:
  name: active-hotspot-oracle-iot
  namespace: helium
spec:
  # Run 30 minutes after the gold table
  schedule: "30 3 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 10
      ttlSecondsAfterFinished: 86400
      template:
        spec:
          serviceAccountName: s3-data-lake-bucket-access
          # Temporarily commenting out to enable log review
          # tolerations: # Schedule executor pods on spot-helium instance group
          #   - key: dedicated
          #     operator: Equal
          #     value: spot-helium
          #     effect: NoSchedule
          nodeSelector:
            nodegroup-type: medium
          containers:
          - name: active-hotspot-oracle-iot
            image: public.ecr.aws/k0m1p4t7/active-hotspot-oracle:0.0.13
            imagePullPolicy: IfNotPresent
            env:
              - name: PRIORITY_FEE_LAMPORTS
                value: "1"
              - name: SOLANA_URL
                valueFrom:
                  secretKeyRef:
                    name: helius-rpc-url
                    key: secret
              - name: ANCHOR_WALLET
                value: /usr/src/app/keys/keypair.json
            args:
              - --aws-bucket
              - foundation-data-lake-requester-pays
              - --aws-region
              - us-west-2
              - --aws-table
              - gold/recently-rewarded-hotspots
              - --sub-dao
              - iot
            volumeMounts:
              - name: active-hotspot-oracle-keypair
                mountPath: /usr/src/app/keys
                readOnly: true
            resources:
              requests:
                cpu: 1000m
                memory: 5Gi
              limits:
                memory: 5Gi
          restartPolicy: OnFailure
          volumes:
            - name: active-hotspot-oracle-keypair
              secret:
                secretName: active-hotspot-oracle-keypair
                items:
                  - key: keypair.json
                    path: keypair.json