apiVersion: batch/v1
kind: CronJob
metadata:
  name: active-hotspot-oracle-iot
  namespace: helium
spec:
  concurrencyPolicy: Forbid
  # Run 30 minutes after the gold table
  schedule: "30 3 * * *"
  jobTemplate:
    spec:
      backoffLimit: 10
      template:
        spec:
          serviceAccountName: s3-data-lake-bucket-access
          tolerations: # Schedule executor pods on spot-helium instance group
            - key: dedicated
              operator: Equal
              value: spot-helium
              effect: NoSchedule
          nodeSelector:
            nodegroup-type: spot-helium
          containers:
          - name: active-hotspot-oracle-iot
            image: public.ecr.aws/k0m1p4t7/active-hotspot-oracle:0.0.12
            imagePullPolicy: IfNotPresent
            env:
              - name: SOLANA_URL
                valueFrom:
                  secretKeyRef:
                    name: rpc-url
                    key: rpc-url
              - name: ANCHOR_WALLET
                value: /usr/src/app/keys/keypair.json
            args:
              - --aws-bucket
              - foundation-data-lake-requester-pays
              - --aws-region
              - us-west-2
              - --aws-table
              - gold/recently-rewarded-hotspots
              - --sub-dao
              - iot
            volumeMounts:
              - name: active-hotspot-oracle-keypair
                mountPath: /usr/src/app/keys
                readOnly: true
            resources:
              requests:
                cpu: 1000m
                memory: 5Gi
              limits:
                memory: 5Gi
          restartPolicy: OnFailure
          volumes:
            - name: active-hotspot-oracle-keypair
              secret:
                secretName: active-hotspot-oracle-keypair
                items:
                  - key: keypair.json
                    path: keypair.json