apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: active-hotspot-oracle-keypair
  namespace: helium
spec:
  encryptedData:
    keypair.json: AgAOWMlRZgy6Q7TXDfgFuI29dOrkbohKrnzPPVRryPY8gw4zSwsh4N+i8s59Fp1JJFCfQwXpP65/LDa7eGy/6vTxNz2A80BZxUdmqfX1oLFF6M6bF4IB8xncRDphWk8v8USkwmjOUuE61opyzZE757s2TACOuw93R+tjjcMIbIVFW/CDxm7LDm+88ukVw5FqW3JV7O2ZWs0s54ns4h16Mj9/zopcNkSLdOGxZErDLLoSw9y1DLPeAU1svPLgHFnU8+0Ve0fXxc1zOMHZAJPXFGrKCkWSyuKPF4pYl9Nxd/MvOxN+b+w5w2lBKwR0Na+Vxh8B4sX/Z/IU1AarqY/5yTVZYlTGcdfR4rR3wEYXbYlkBHmAhSEeVOyDfWqyKs5OZExWt4h+wMpAnxpoeSzI/numPWAaSFe8ts/0vpm20n36417wwuu1CRje/G7dnk5HtSmCCKeO/TReScmxOf63IcheegKJo07XTl2sz0Rme2JsC9wpWghYpaGI2IJR5UqERVWZtySYm6W0imkHqjip//mLyDnXqVubT6KH4J1i8/lN0Wj3iZ2mgA4Rd2HyqBwf3uburDPr46rdIapKMwkyL/x9RbWdAX1/7yIf78PGqOzGUCUWLXVDe9z+jT2t4cNMNLKNbpwUQmnYSZ9DUDLD9/WpK8ge5xnD4ieOQwPL7ep4lJSMb/2qhBli1tZOAnojgNRx+yKgjdE2HFHwbCcF4nsfEHdGwA3sF4Iu/Ul1K4BEZJ3733+BCph/VJFho93echf5hb3FdyiOAcVEZpX2bbvUCazaqxXwxqhmHauU/By3/UrA0Sno3DZDZ7FjtNyU0SkNeULaGvcEWQXUQwIxSMW5XEZOcUXUWPaktFvdouBT46SwYv04cWok8m2o9mBsmW0uhlXO13ebYqOJ+7vY0EYVZ5Swgl9FoNw2t81fkbR26Lqdjj1A6gfDwYrYh4re8Jm5fmgrzf6tBA6Ro2E3PV18L6b3bEGtE5pzi+qv3kg47ew=
  template:
    metadata:
      creationTimestamp: null
      name: active-hotspot-oracle-keypair
      namespace: helium

