apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helium
  namespace: argocd
spec:
  destination:
    namespace: helium
    server: https://kubernetes.default.svc
  project: helium
  source:
    repoURL: https://github.com/helium/helium-foundation-k8s
    path: argocd/manifests/helium
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true