apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: argo
  namespace: argocd
  annotations:
    external-dns.alpha.kubernetes.io/hostname: argo.test-helium.com
spec:
  rules:
  - host: argo.test-helium.com
    https:
      paths:
      - backend:
          serviceName: argocd-server
          servicePort: 443
