apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo
  namespace: argocd
  annotations:
    external-dns.alpha.kubernetes.io/hostname: argo.test-helium.com
spec:
  rules:
  - host: argo.test-helium.com
    https:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: argocd-server
            port: 443
