apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mobile-oracle
  name: mobile-oracle
  namespace: helium
spec:
  selector:
    matchLabels:
      app: mobile-oracle
  template:
    metadata:
      labels:
        app: mobile-oracle
        security-group: rds-access
    spec:
      serviceAccountName: rds-mobile-oracle-user-access
      containers:
        - name: mobile-oracle
          image: public.ecr.aws/j4f9f0n7/distributor-oracle:0.0.24
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          env:
            - name: ANCHOR_PROVIDER_URL
              valueFrom:
                configMapKeyRef:
                  name: globals
                  key: solana_url
            - name: ORACLE_KEYPAIR_PATH
              value: /usr/src/app/keys/keypair.json
            - name: PGDATABASE
              value: mobile_index
            - name: PGHOST
              value: oracle-rds.cjfnfp6fnm1y.us-west-2.rds.amazonaws.com
            - name: PGPORT
              value: "5432"
            - name: PGUSER
              value: mobile_oracle
            - name: AWS_REGION
              value: us-west-2
            - name: ASSET_API_URL
              valueFrom:
                configMapKeyRef:
                  name: globals
                  key: asset_api_url
          volumeMounts:
            - name: oracle-keypair
              mountPath: /usr/src/app/keys
              readOnly: true
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 250m
              memory: 500Mi
            limits:
              cpu: 500m
              memory: 750Mi
      volumes:
        - name: oracle-keypair
          secret:
            secretName: oracle-keypair
            items:
              - key: keypair.json
                path: keypair.json
---
apiVersion: v1
kind: Service
metadata:
  name: mobile-oracle
  namespace: helium
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: http
  selector:
    app: mobile-oracle
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mobile-oracle
  namespace: helium
spec:
  ingressClassName: nginx
  rules:
  - host: mobile-rewards.oracle.helium.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mobile-oracle
            port:
              number: 8080
