---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: helius-rpc-url
  namespace: helium
spec:
  encryptedData:
    secret: AgBQkPMNIZrVfjeHCXVSFZQAR5J1jEtDolD0KydWJPqt5+lgSYFbuko6Y+1cZbYTB0+1USQJEuIMCYTW8juUuyHdgXw+fTcr3h7X4/r6NV3wDc/fqSWsT1JOJV4vXY8R1XLWxRguOWNbnoCYDT0BH68X04MpjogHuZq8DPjaU3YncPsSQGKzg4LTGg0+pebD/b0haMewYyr1fglCgXTwSo5ecN7xzWrHRoGoE+4OZXfqmu81CflBVdt3IB1qSgboBE4E9uowQSaTp19nrnSYqvuYMl5lmkOyX260MUrBDTWNY75DvcFqncEO/7jGU68a7dnXjS1XtzaYFiZ9rGSAy4cp1mwD1BXPwSVDsCYN3hCZYO7qkdWdsOGqbVZOzqPMag3vOc0D7WuWXBjo/yz8b5Bi1MSw9Oh2gQI39BYPjbsT/pAbuiCMV7wuLnq6IYazOWAOWnQP1LntnpKHR8lWH9LGn/ZU1Re/OCbJX68YtZCEUq8ncHnf0iQU6/MQDyjiu80cSQxDNAfIaHBGoVFVjZfq5nzj6hHJzF5sHudXEwCB7Ims/Z5/zBCEs3PYn1wh7di3Cu+JMVSAmxfVnXTQHWs9nqxwyHqlbhXkmXQdi+agg3WFZb9zJYwfPqWqPzwGUJgnVJ7gFfu77/VNwTbz6NmfqbxjYHZSU/0sMM2o3pzWPMt9qqu0QclO5/ZfBuNkepUTzBlxvpBrCYPGpya7bV+fe50477txeCdOq5WNi8bD3iB1sfYCz4E6jiSoTyntqc82wGUYsH0TV7TlZ3sfNF+SS9KowfLxyNu+aA==
  template:
    metadata:
      creationTimestamp: null
      name: helius-rpc-url
      namespace: helium
