---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: refresh-password
  namespace: helium
spec:
  encryptedData:
    password: AgBKQxXYJC1mcfyvha9m7H2xgVRp3BRXWiP6KPQq15EezMJlyxT1znxtpabSPHUhIiIWTFArYewQLG2QjK5cOGC2lmQKUGyuyzruRv7iQ2HSTWCdSwyMcupb5CKjsgbQxmJpDSSSVLgeRv5ZSjR56q4ticXw4LWttB7Fx1PZAylR7fMUFZJdz9qOjV/ZtrnsFP/90EFUJWmbL/0uiCE054ncBxzVF3fPohhqA7fXwiAiVXxky1xGWYi2jlZLvyLmaott+g66X8xX0m6Dcu9hWUhS4F7fu1vAFRDUeC15AcZcxeiMJ4GUhsJj908OWgYLmnnewLq1Z6O3eAcCjolMpy/df0T1KOky75gh/TLPgSR30enil4aYJKXCB4saFiG9V5dYvBAv5WlmQ/TcJddTAy6tDXOr5Y0cYeaCk82knSEda10fYbSzwjbhJkYzZM4V+mw9gM9YdC6qcFqDezboWgrnDTm3Dtw1rIROZt2/16cBDcDIyNyMDjre9PrA8lhU2HRTFKXKZGtzQG+wjyvV7BX+FLqC78wTl8ZeEhrbCvfOsoX1ugbup9YrrlcnggQfjfR9Ja/PE3senF/9voXtopBDoESJszlWkzhh1tJhGhrOyL/da+axe0oQMe80n4gnBMQYE4miKtuMrYqoXGOvDuIBBOPoHmcdDS/Rl4bUW85Iwv19jOy/GvkuM61xHXpV3ncuTFwM05YTFw==
  template:
    metadata:
      creationTimestamp: null
      name: refresh-password
      namespace: helium
