apiVersion: v1
kind: ConfigMap
metadata:
  name: globals
  namespace: helium
data:
  solana_url: "https://api.devnet.solana.com"
  asset_api_url: "https://rpc-devnet.aws.metaplex.com/"
  mobile_mint: "mb1eaxqRn3VMUuA9MC1hXiNFG7hnJHfF8Cvq7vfYH4y"
  iot_mint: "iotfeTXUVZKZvmFCTTHrgmep94seQJurjvMgKuqpHyx"
  hnt_mint: "hntv1Vf5ZBG777xAHqHUTFS8UZBTNUN22MBnYramPFk"
  dc_mint: "dc5Zu977Zan2BFt7iLxCCUoyPvxpxZGYK23d6GYZXq7"
  mobile_rewards: "50"
