apiVersion: v1
kind: ConfigMap
metadata:
  name: globals
  namespace: helium
data:
  solana_url: "https://monke8127d577985245538ac648fe0969201d.xyz2.hyperplane.dev/"
  mobile_mint: "6TR9fVX4NSB774cNAhShxdsx3MMVaCn2aoerZ7J47BMq"
  hnt_mint: "EN1yLvjyFrHAWnHkb2WPagZ4pZh15GHnZTGfP5NDNbBP"
  dc_mint: "GDFcdntstJxxpTqPptdpJXSgeoFjdpRbK49agWkgTaCr"
  mobile_rewards: "50"
