apiVersion: v1
kind: ConfigMap
metadata:
  name: globals
  namespace: helium
data:
  solana_url: "https://api.devnet.solana.com"
  mobile_mint: "783c5RUqWpoioXZujWmas97hVVom5BpMncsBcbnPVfyR"
  hnt_mint: "Fd1ceDiVgfRQw3j9HAn3aarrkqUqTgHRBbHStRp1u2ck"
  dc_mint: "CnU1ySY7q5qgYowLACz23d515wwakiEt5ujx8k1f6E34"
  mobile_rewards: "50"
