apiVersion: v1
kind: ConfigMap
metadata:
  name: globals
  namespace: helium
data:
  solana_url: "https://api.devnet.solana.com"
  mobile_mint: "FPKgDamvsNjfmYqjUwkFREXeKGoLFmD4NcQ68kRtSxrs"
  hnt_mint: "CD9XaohcmnM3Xc95VvK5w1jm5ZuQ6wovy4uAYQ39jS2S"
  dc_mint: "4R2prERdggRzHw9boXqmbff1fzjzXW5aX7pNtjMdYNrr"
  mobile_rewards: "50"
