apiVersion: v1
kind: ConfigMap
metadata:
  name: globals
  namespace: helium
data:
  solana_url: "https://mplx-devnet.genesysgo.net"
  mobile_mint: "4RFxp35ijn9QzGV2GAWRnJmMp1kcZ5YgZuBwk3WWZzYf"
  hnt_mint: "5Ts6pmWMsqsz9sxyZ6BRVMZtxhU8Pizf2F4cHZEeJiuv"
  dc_mint: "FyKCf3SQ3DNzfWRoueVcQFicU6QTj16sC6nrmQ2KYnjk"
  mobile_rewards: "50"
