apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: oracle-keypair
  namespace: helium
spec:
  encryptedData:
    keypair.json: AgBNpKn2Mgl3knXFEJDhJU/ZLQ1gS0h3uUQ7g8JXPBd9fplujJliZSthQVldekNFUiKeC25gTMppz2kZ09WzocpdaWyPN8KQ9Jwnz/GCp1J0wspil1CRS5L/6UGa69CtvQ0u8QKGZ8lVEDwO5AI8wMgnx2UYhREHaXeytrF1A3S1vgGOPWbzeYslaiIYqpio/5RKLKTQBVaPQAqOOM+DrHZEVewQWHZIxiDitn3VWV0ImJ2QRvSaogT0ixfVrrS+esnh042Qkfj5nkDkwBeAohmyawscQxxJfXX6pTTwx2yogr4VA2y4/vjp/jrcBmOUTCcDMMjOG9th+nBEEEDbNwAVUB4FAzKddZXjBVzZAQUsrcPH2XNQPrzSQptw8QG6oDmoeIxOqOPbTlsYi7KUj1PohM5cLcNtj6rO+Qm8LcFjaZFium7Nmi49L5VXtgeYNBzskiuIgakCkiraD5bsmlxol+ak4b/Ni2YH8hf8wyp+H/Bfye7obKmA1UMf/L55lIFiFhjFqUk42RvSNib3pNXowCawjTS8i4Qx7J/P0T1lueYxxvHDCA+BJrjonYzMMw95jYITn29it/17PQrA37RopWX6sS97NTH0993FOA1h//3TteX87GR8lNiu6IVX0qxqTYidqutUulikmXvMcmhT87EpTUH7gXZwKX4gn2W+oqsLR1sMb6v+eYb8YwYFTFWl+ueiYYbO7AA+RtbfhVG4/sHUfQqK9b6l7Y3EytafRnCrYDuc0i69oqXOfHYYxli5qyrrZaGeuTjkdA1921oPXWcMQxLDB+jkKM47/toTVcio2oQnq8w6U/gce0oplnyQKsgnsQyEYH5bEyNDlEbfPb/utkKgoLuGD9fo6npNr0JlglN5Lr+qSNrSQBgszk6akcgm2hic2e8Zmhq+xOtgv6C4Ko+ki/2ciA1IAOhPjEYozgAS5YSJE2usMWuJjjG0xfUkMHFcqUcqcHrso9agH681hrgkORgPbCO9CjzARBp/IN0m8RY=
  template:
    metadata:
      creationTimestamp: null
      name: oracle-keypair
      namespace: helium

