apiVersion: v1
kind: ConfigMap
metadata:
  name: hotspot-rewards-silver-query
  namespace: spark
data:
  query.sql: |
    SELECT 
      max(end_period) as most_recent_ts, 
      b58encodeChecked(gateway_reward.hotspot_key) as hotspot_key 
    FROM iot_reward_share
    GROUP BY hotspot_key;
---
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: hotspot-rewards-silver
  namespace: spark
spec:
  type: Scala
  mode: cluster
  image: "public.ecr.aws/k0m1p4t7/spark:v3.4.0-aws"
  imagePullPolicy: Always
  mainClass: Main
  mainApplicationFile: "s3a://foundation-data-lake-requester-pays/jars/spark-streaming-sql-assembly-1.0.jar"
  sparkVersion: "3.4.0"
  restartPolicy:
    type: Never
  sparkConf:
    spark.databricks.delta.autoCompact.enabled: "true"
  hadoopConf:
    fs.s3a.aws.credentials.provider: com.amazonaws.auth.WebIdentityTokenCredentialsProvider
  volumes:
    - name: "tmp"
      hostPath:
        path: "/tmp"
        type: Directory
    - name: config-vol
      configMap:
        name: hotsopt-rewards-silver-query
        items:
          - key: query.sql
            path: query.sql
  driver:
    serviceAccount: spark-data-lake-access
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    envVars:
      TABLE_IOT_REWARD_SHARE: s3a://foundation-data-lake-requester-pays/bronze/iot_reward_share
      CHECKPOINT: s3a://foundation-data-lake-requester-pays/checkpoints/hotspot-rewards-silver
      OUTPUT: s3a://foundation-data-lake-requester-pays/silver/hotspot-rewards
      QUERY_PATH: /app/query.sql
      BATCH_PROCESSING: true
    labels:
      version: 3.4.0
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
      - name: config-vol
        mountPath: /app
  executor:
    serviceAccount: spark-data-lake-access
    cores: 1
    coreLimit: "1200m"
    instances: 3
    memory: "6G"
    labels:
      version: 3.4.0
    volumeMounts:
      - name: "tmp"
        mountPath: "/tmp"