apiVersion: v1
kind: ConfigMap
metadata:
  name: recently-rewarded-hotspots-gold-query
  namespace: spark
data:
  query.sql: |
    SELECT
      max(end_period) as most_recent_ts, 
      entity_key,
      'iot' as sub_dao
    FROM iot_hotspot_rewards
    WHERE date >= date_sub(current_date(), 62) -- Pull a little more than two months so we also get transitioning hotspots
          AND (beacon_amount > 0 OR witness_amount > 0 OR dc_transfer_amount > 0)
    GROUP BY entity_key
    UNION ALL
    SELECT
      max(end_period) as most_recent_ts, 
      entity_key,
      'mobile' as sub_dao
    FROM mobile_hotspot_rewards
    WHERE date >= date_sub(current_date(), 62) -- Pull a little more than two months so we also get transitioning hotspots
          AND (poc_amount > 0 OR dc_transfer_amount > 0)
    GROUP BY entity_key;
---
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: ScheduledSparkApplication
metadata:
  name: recently-rewarded-hotspots-gold
  namespace: spark
spec:
  # Run 30 minutes before the end of epoch
  schedule: "30 23 * * *"
  concurrencyPolicy: Forbid
  successfulRunHistoryLimit: 1
  failedRunHistoryLimit: 5
  template:
    type: Scala
    mode: cluster
    image: "public.ecr.aws/k0m1p4t7/spark:v3.4.0-aws"
    imagePullPolicy: Always
    mainClass: Main
    mainApplicationFile: "s3a://foundation-data-lake-requester-pays/jars/spark-streaming-sql-assembly-1.0.2.jar"
    sparkVersion: "3.4.0"
    restartPolicy:
      type: OnFailure
      onFailureRetries: 3
      onFailureRetryInterval: 10
      onSubmissionFailureRetries: 3
      onSubmissionFailureRetryInterval: 10
    sparkConf:
      spark.databricks.delta.autoCompact.enabled: "true"
    hadoopConf:
      fs.s3a.aws.credentials.provider: com.amazonaws.auth.WebIdentityTokenCredentialsProvider
    volumes:
      - name: "tmp"
        hostPath:
          path: "/tmp"
          type: Directory
      - name: config-vol
        configMap:
          name: recently-rewarded-hotspots-gold-query
          items:
            - key: query.sql
              path: query.sql
    driver:
      serviceAccount: spark-data-lake-access
      cores: 1
      coreLimit: "1200m"
      memory: "512m"
      envVars:
        TABLE_MOBILE_HOTSPOT_REWARDS: s3a://foundation-data-lake-requester-pays/silver/mobile-hotspot-rewards
        TABLE_IOT_HOTSPOT_REWARDS: s3a://foundation-data-lake-requester-pays/silver/iot-hotspot-rewards
        OUTPUT: s3a://foundation-data-lake-requester-pays/gold/recently-rewarded-hotspots
        QUERY_PATH: /app/query.sql
        BATCH_PROCESSING: "true"
        TRIGGER: AvailableNow
      labels:
        version: 3.4.0
      volumeMounts:
        - name: "test-volume"
          mountPath: "/tmp"
        - name: config-vol
          mountPath: /app
    executor:
      serviceAccount: spark-data-lake-access
      cores: 1
      coreLimit: "1200m"
      instances: 3
      memory: "6G"
      labels:
        version: 3.4.0
      volumeMounts:
        - name: "tmp"
          mountPath: "/tmp"