{
 "title": "Helium Solana Dash",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Treasuries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Mobile Treasury Balance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "HNT" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_account_balance{name=\"mobile_treasury\"}"
    }
   ]
  },
  {
   "title": "Mobile Rewards Escrow",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "MOBILE" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_account_balance{name=\"mobile_rewards_escrow\"}"
    }
   ]
  },
  {
   "title": "IOT Treasury Balance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "HNT" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_account_balance{name=\"iot_treasury\"}"
    }
   ]
  },
  {
   "title": "IOT Rewards Escrow",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "IOT" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_account_balance{name=\"iot_rewards_escrow\"}"
    }
   ]
  },
  { "title": "Token Supply", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "HNT Supply",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "HNT" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_mint_supply{name=\"hnt\"}"
    }
   ]
  },
  {
   "title": "Mobile Supply",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "MOBILE" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_mint_supply{name=\"mobile\"}"
    }
   ]
  },
  {
   "title": "IoT Supply",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "IOT" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_mint_supply{name=\"iot\"}"
    }
   ]
  },
  {
   "title": "DC Supply",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "DC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_mint_supply{name=\"dc\"}"
    }
   ]
  },
  { "title": "Circuit Breakers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "HNT Mint Breaker",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solana_circuit_breaker_level{name=\"hnt_mint\"}",
     "legendFormat": "level"
    },
    {
     "expr": "solana_circuit_breaker_limit{name=\"hnt_mint\"}",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "DC Mint Breaker",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solana_circuit_breaker_level{name=\"dc_mint\"}",
     "legendFormat": "level"
    },
    {
     "expr": "solana_circuit_breaker_limit{name=\"dc_mint\"}",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Mobile Treasury Breaker",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "solana_circuit_breaker_level{name=\"mobile_treasury\"}",
     "legendFormat": "level"
    },
    {
     "expr": "solana_circuit_breaker_limit{name=\"mobile_treasury\"}",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "IOT Treasury Breaker",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "solana_circuit_breaker_level{name=\"iot_treasury\"}",
     "legendFormat": "level"
    },
    {
     "expr": "solana_circuit_breaker_limit{name=\"iot_treasury\"}",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Mobile Mint Breaker",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "solana_circuit_breaker_level{name=\"mobile_mint\"}",
     "legendFormat": "level"
    },
    {
     "expr": "solana_circuit_breaker_limit{name=\"mobile_mint\"}",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "IOT Mint Breaker",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "solana_circuit_breaker_level{name=\"iot_mint\"}",
     "legendFormat": "level"
    },
    {
     "expr": "solana_circuit_breaker_limit{name=\"iot_mint\"}",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Mobile Escrow Breaker",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "solana_circuit_breaker_level{name=\"mobile_rewards_escrow\"}",
     "legendFormat": "level"
    },
    {
     "expr": "solana_circuit_breaker_limit{name=\"mobile_rewards_escrow\"}",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "IOT Escrow Breaker",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "solana_circuit_breaker_level{name=\"iot_rewards_escrow\"}",
     "legendFormat": "level"
    },
    {
     "expr": "solana_circuit_breaker_limit{name=\"iot_rewards_escrow\"}",
     "legendFormat": "limit"
    }
   ]
  }
 ]
}