apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - grafana.yaml
configMapGenerator:
- name: grafana-datasources
  files:
    - datasources.yaml
- name: grafana-dashboards
  files:
    - dashboards/dashboard.yaml
    - dashboards/solana.yaml
