{
 "title": "Helium Solana Dash",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Mobile Treasury Balance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "solana_account_balance{name=\"mobile_treasury\"}"
    }
   ]
  },
  {
   "title": "Mobile Rewards Escrow",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "solana_account_balance{name=\"mobile_rewards_escrow\"}"
    }
   ]
  },
  {
   "title": "Mobile Supply",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "solana_mint_supply{name=\"mobile\"}"
    }
   ]
  },
  {
   "title": "HNT Supply",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "solana_mint_supply{name=\"hnt\"}"
    }
   ]
  },
  {
   "title": "DC Supply",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "solana_mint_supply{name=\"dc\"}"
    }
   ]
  },
  {
   "title": "Mobile Treasury Breaker",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solana_circuit_breaker_level{name=\"mobile_treasury\"}",
     "legendFormat": "level"
    },
    {
     "expr": "solana_circuit_breaker_limit{name=\"mobile_treasury\"}",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "HNT Mint Breaker",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 11, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solana_circuit_breaker_level{name=\"hnt_mint\"}",
     "legendFormat": "level"
    },
    {
     "expr": "solana_circuit_breaker_limit{name=\"hnt_mint\"}",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "DC Mint Breaker",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solana_circuit_breaker_level{name=\"dc_mint\"}",
     "legendFormat": "level"
    },
    {
     "expr": "solana_circuit_breaker_limit{name=\"dc_mint\"}",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Mobile Escrow Breaker",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solana_circuit_breaker_level{name=\"mobile_rewards_escrow\"}",
     "legendFormat": "level"
    },
    {
     "expr": "solana_circuit_breaker_limit{name=\"mobile_rewards_escrow\"}",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Mobile Mint Breaker",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solana_circuit_breaker_level{name=\"mobile_mint\"}",
     "legendFormat": "level"
    },
    {
     "expr": "solana_circuit_breaker_limit{name=\"mobile_mint\"}",
     "legendFormat": "limit"
    }
   ]
  }
 ]
}