apiVersion: v1
kind: ConfigMap
metadata:
  name: account-postgres-sink-config
  namespace: helium
data:
  config.json: |
    {
      "configs": [
        {
          "programId": "hemjuPXBpNvggtaUnN1MwT3wrdhttKEfosTcc2P9Pg8",
          "accounts": [
            {
              "type": "KeyToAssetV0",
              "table": "key_to_assets",
              "schema": "public"
            },
            {
              "type": "IotHotspotInfoV0",
              "table": "iot_hotspot_infos",
              "schema": "public"
            },
            {
              "type": "MobileHotspotInfoV0",
              "table": "mobile_hotspot_infos",
              "schema": "public"
            }
          ],
          "crons": [
            { "schedule": "0 0 * * *", "type": "integrity-check" }
          ]
        }
      ]
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: account-postgres-sink-service
  name: account-postgres-sink-service
  namespace: helium
spec:
  selector:
    matchLabels:
      app: account-postgres-sink-service
  replicas: 1
  template:
    metadata:
      labels:
        app: account-postgres-sink-service
        security-group: rds-access
    spec:
      serviceAccountName: rds-metadata-user-access
      containers:
        - name: account-postgres-sink-service
          image: public.ecr.aws/v0j6k5v6/account-postgres-sink-service:0.0.47
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          env:
            - name: RUN_JOBS_AT_STARTUP
              value: "true"
            - name: PGHOST
              value: oracle-rds.cf49lv1xslmw.us-east-1.rds.amazonaws.com
            - name: PGPORT
              value: "5432"
            - name: PGUSER
              value: metadata
            - name: AWS_REGION
              value: us-east-1
            - name: PGDATABASE
              value: metadata
            - name: PGSSLMODE
              value: no-verify
            - name: SOLANA_URL
              valueFrom:
                configMapKeyRef:
                  name: globals
                  key: solana_url
            - name: ASSET_API_URL
              valueFrom:
                configMapKeyRef:
                  name: globals
                  key: asset_api_url
            - name: PROGRAM_ACCOUNT_CONFIGS
              value: "/usr/src/app/config/config.json"
            - name: HELIUS_AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: helius-auth-secret
                  key: secret
          volumeMounts:
            - name: account-postgres-sink-config
              mountPath: /usr/src/app/config
              readOnly: true
          resources:
            requests:
              cpu: 250m
              memory: 500Mi
            limits:
              memory: 2Gi
      volumes:
        - name: account-postgres-sink-config
          configMap:
            name: account-postgres-sink-config
            items:
              - key: config.json
                path: config.json
---
apiVersion: v1
kind: Service
metadata:
  name: account-postgres-sink-service
  namespace: helium
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: http
  selector:
    app: account-postgres-sink-service
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: account-postgres-sink-service
  namespace: helium
spec:
  ingressClassName: nginx
  rules:
    - host: account-sink.oracle.test-helium.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: account-postgres-sink-service
                port:
                  number: 3000
