apiVersion: v1
kind: ConfigMap
metadata:
  name: account-postgres-sink-alternative-config
  namespace: helium
data:
  config.json: |
    {
      "configs": [
        {
          "programId": "hemjuPXBpNvggtaUnN1MwT3wrdhttKEfosTcc2P9Pg8",
          "accounts": [
            {
              "type": "KeyToAssetV0",
              "table": "key_to_assets",
              "schema": "public",
              "batchSize": 25000
            },
            {
              "type": "IotHotspotInfoV0",
              "table": "iot_hotspot_infos",
              "schema": "public",
              "batchSize": 25000
            },
            {
              "type": "MobileHotspotInfoV0",
              "table": "mobile_hotspot_infos",
              "schema": "public",
              "batchSize": 25000
            }
          ],
          "crons": [
            { "schedule": "10 0 * * *", "type": "integrity-check" }
          ]
        },
        {
          "programId": "hexbnKYoA2GercNNhHUCCfrTRWrHjT6ujKPXTa5NPqJ",
          "accounts": [
            {
              "type": "BoostConfigV0",
              "table": "boost_configs",
              "schema": "public"
            },
            { "type": "BoostedHexV0", "table": "boosted_hexes", "schema": "public" }
          ]
        },
        {
          "programId": "hdaoVTCqhfHHo75XdAMxBKdUqvq1i5bF23sisBqVgGR",
          "accounts": [
            { "type": "DaoEpochInfoV0", "table": "dao_epoch_infos", "schema": "public" },
            { "type": "SubDaoEpochInfoV0", "table": "sub_dao_epoch_infos", "schema": "public" }
          ],
          "crons": [
            { "schedule": "10 0 * * *", "type": "integrity-check" }
          ]
        }
      ]
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: account-postgres-sink-alternative-service
  name: account-postgres-sink-alternative-service
  namespace: helium
spec:
  selector:
    matchLabels:
      app: account-postgres-sink-alternative-service
  replicas: 1
  template:
    metadata:
      labels:
        app: account-postgres-sink-alternative-service
        security-group: rds-access
    spec:
      serviceAccountName: rds-metadata-user-access
      containers:
        - name: account-postgres-sink-alternative-service
          image: public.ecr.aws/v0j6k5v6/account-postgres-sink-service:0.3.37
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          env:
            - name: RUN_JOBS_AT_STARTUP
              value: "true"
            - name: PG_HOST
              value: oracle-rds.cf49lv1xslmw.us-east-1.rds.amazonaws.com
            - name: PG_PORT
              value: "5432"
            - name: PG_USER
              value: metadata
            - name: AWS_REGION
              value: us-east-1
            - name: PG_DATABASE
              value: metadata
            - name: PG_SSL_MODE
              value: no-verify
            - name: SOLANA_URL
              valueFrom:
                secretKeyRef:
                  name: helius-rpc-url
                  key: secret
            - name: ASSET_API_URL
              valueFrom:
                secretKeyRef:
                  name: helius-rpc-url
                  key: secret
            - name: PROGRAM_ACCOUNT_CONFIGS
              value: "/usr/src/app/config/config.json"
            - name: HELIUS_AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: helius-auth-secret
                  key: secret
          volumeMounts:
            - name: account-postgres-sink-alternative-config
              mountPath: /usr/src/app/config
              readOnly: true
          resources:
            requests:
              cpu: 1000m
              memory: 2Gi
            limits:
              memory: 5Gi
      volumes:
        - name: account-postgres-sink-alternative-config
          configMap:
            name: account-postgres-sink-alternative-config
            items:
              - key: config.json
                path: config.json
---
apiVersion: v1
kind: Service
metadata:
  name: account-postgres-sink-alternative-service
  namespace: helium
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: http
  selector:
    app: account-postgres-sink-alternative-service
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: account-postgres-sink-alternative-service
  namespace: helium
spec:
  ingressClassName: nginx
  rules:
    - host: account-sink-alternative.oracle.test-helium.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: account-postgres-sink-alternative-service
                port:
                  number: 3000
