apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: iot-oracle
  name: iot-oracle
  namespace: helium
spec:
  selector:
    matchLabels:
      app: iot-oracle
  template:
    metadata:
      labels:
        app: iot-oracle
        security-group: rds-access
    spec:
      serviceAccountName: rds-iot-oracle-user-access
      containers:
        - name: iot-oracle
          image: public.ecr.aws/s2o4r1i6/distributor-oracle:0.0.50
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          env:
            - name: ANCHOR_PROVIDER_URL
              valueFrom:
                secretKeyRef:
                  name: rpc-url
                  key: rpc-url
            - name: ORACLE_KEYPAIR_PATH
              value: /usr/src/app/keys/keypair.json
            - name: PGDATABASE
              value: iot_index
            - name: PGHOST
              value: oracle-rds.cf49lv1xslmw.us-east-1.rds.amazonaws.com
            - name: PGPORT
              value: "5432"
            - name: PGUSER
              value: iot_oracle
            - name: AWS_REGION
              value: us-east-1
            - name: ASSET_API_URL
              valueFrom:
                secretKeyRef:
                  name: rpc-url
                  key: rpc-url
            - name: DNT_MINT
              valueFrom:
                configMapKeyRef:
                  name: globals
                  key: iot_mint
          volumeMounts:
            - name: oracle-keypair
              mountPath: /usr/src/app/keys
              readOnly: true
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              memory: 300Mi
      volumes:
        - name: oracle-keypair
          secret:
            secretName: oracle-keypair
            items:
              - key: keypair.json
                path: keypair.json
---
apiVersion: v1
kind: Service
metadata:
  name: iot-oracle
  namespace: helium
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: http
  selector:
    app: iot-oracle
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: iot-oracle
  namespace: helium
  annotations:
    nginx.ingress.kubernetes.io/limit-rps: "10"
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "10"
spec:
  ingressClassName: nginx
  rules:
  - host: iot-rewards.oracle.test-helium.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: iot-oracle
            port:
              number: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: iot-oracle
  namespace: helium
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: iot-oracle
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75