apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mobile-rewards-faucet
  name: mobile-rewards-faucet
  namespace: helium
spec:
  selector:
    matchLabels:
      app: mobile-rewards-faucet
  template:
    metadata:
      labels:
        app: mobile-rewards-faucet
        security-group: rds-access
    spec:
      serviceAccountName: rds-mobile-oracle-user-access
      containers:
        - name: mobile-rewards-faucet
          image: public.ecr.aws/s2o4r1i6/rewards-oracle-faucet-service:0.0.5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          env:
            - name: ANCHOR_PROVIDER_URL
              valueFrom:
                configMapKeyRef:
                  name: globals
                  key: solana_url
            - name: PGDATABASE
              value: mobile_index
            - name: PGHOST
              value: oracle-rds.cf49lv1xslmw.us-east-1.rds.amazonaws.com
            - name: PGPORT
              value: "5432"
            - name: PGUSER
              value: mobile_oracle
            - name: AWS_REGION
              value: us-east-1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3000
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 250m
              memory: 500Mi
            limits:
              cpu: 500m
              memory: 750Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mobile-rewards-faucet
  namespace: helium
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: http
  selector:
    app: mobile-rewards-faucet
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mobile-rewards-faucet
  namespace: helium
  annotations:
    nginx.ingress.kubernetes.io/limit-rps: "1"
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "3"
spec:
  ingressClassName: nginx
  rules:
  - host: mobile-rewards-faucet.oracle.test-helium.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mobile-rewards-faucet
            port:
              number: 3000
