apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: oracle-keypair
  namespace: helium
spec:
  encryptedData:
    keypair.json: AgAtOpxUJczivUOJNU5ScbD4pErkYwsO8szsrKospZYe73arq7Wh7ZEGsvrstTSMVqycUP2IrMeELxvRTJev0JTyKmX9veDU+kfhS4sN9bnKGLoAlb6aqlstgcIUFW5FrIb4RtBBHqKyQGh6DyQObj3uovdbPPbkrFrPPTaQ2BrLY6/ZPKuOqgEHi/2S11iz2nq3Qj21wnsULG/Vq+KpSh3HlcEAjIk2DY+4aYo6IkA/eYkF1O4tbiJJlEGLe+rvkK5Efpt/beGUThQRPYaupoxIxjcrZBEDVv5kccT+MRQ2kLvvCEWfZY3/wBn8STOifoeykTEYw/unvv6vsUQ/sGj44PSdjpzqKwUT94C04Asn8Zxz27/diiOSUkxHvN4g501CMLnhpUj5Cdu/L3Y2QceCi/gzVPcJY+C3tuzsRLMzdmfwyNyHXfcnrVW1Fc45wu1HHi3JdHtz9SZ3DGTcJi+omQ1jzy0WH1YHPK2sgqkc2OB9++kMEepymy/lmEl1GLqt0EAdSAcs/5SzUgMCLK1eZgEFmXfTRfSPC+qMpI0uub100Rf1XhlJx5k/6J9tWNNsleroiVjkVgnib0y7d/Lfz35aFEcL51W5in6vf2AgmnuB9rF/SmxMlaBSGpSSOVZQF2rvVu4DAOypqqA9oTYbxJkqHngELszlELnlXqHDgiGxKIopgkPKre9xK+qXgE14SljDRqjcYb2BvRn1HNsH9EJbRBRiP7kUz5csOq2HwVmrNQl9Pr58vpzp2BbABwtSDfEHm5LtpasrsOwwGdbSvQYFaCe4+Y+w9ihnvKogNbbZc8d6MfwiI/L2BjjIZeLkzUbTWBzQDtfIVL2XmEHEf4mTV+7VNVvMD239XHoLanGYRYX8i/VOUwzjjxQ9VJby0aaZYObjsGmrkpX8Nu46/9YyN+51EkqNyWF77AkHVlDRIcrpe/S7PYlNkPC4DKO6aLbN89xN1u4NX0FVD8SOVmOWQp2Z+U63qpNE8NOb074bK0Zec8mm
  template:
    metadata:
      creationTimestamp: null
      name: oracle-keypair
      namespace: helium

