apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: oracle-keypair
  namespace: helium
spec:
  encryptedData:
    keypair.json: AgClN62Ijo0s6U2N140/B8/8hqrfA3FCTrbQsKmH1kce8hxfi30EdWF76ONgssmSSvdzfZ+d8bQlSO9nEc6pIF7PII+fDkPI0M3gwgx1yNV5Rv7rdT97S8TIJRJwhvCQ64txVvK5QRPM7FHXE6lorLE2tBPRnWlGpSvRvlzv02EKOepz60xoRWa6pYx/M6cEJxwYKMhZlFhAI/BfjTOxOXUG+eV994X3+pRhh/rtT2o/XKQ4eNqhXiu6b7THkl40RJbf9IaNQl6YSH9+EPLc6BpGCCvd5+tn3/UzY7tYUnCXOaKhxhEH2Z0i3k/93EiOUUvAYzdkLdBBNNizMNZVOcHEKprFbAH4zPzGM/ZEQZzjX7VsOwjCa6Axwcj2nLtyiUIpw0jIBR1OrPm1UEFqdQ4cOhCEpxT0tikANle1aSyEmv2ly5FjI5Ud8yARi5jWsytK5RDCpBmbd1V/cGOQ+7e1EgDKzmxdye9MF3jTG8xs7aBRUFs8ipZe4bB7WOKiFFgKkvwZbOqrlJIVIZT5GQDDcm3ZVipxJ77xu1u6kMZ8s8Lk38ZC6blcOCjYOLKiw4a1zw6vtkWr2Uo+HWBGOvPKdNy0WGUyUbU7uZlVgBNzTrRfqKK9KdEazbedc9QxqGpwcDu6xebp1mNUKa3zB9Izh38MsKpTNfUSI3n8YnE5BtZRYHRJQzIWs7P/9l1+L7/nWpylbVAPAsOG1IQQ8unekN9Gu03QhiDVxOv8npdvSauF1FLqUaOlcZkcWPeUyg2bzDhHdsmB6kzpibb3nwu4VsPFjJ/DNN/5PxamDxA12PCd6wT6TVo4DeTr/pz4QEh3TtLCHakr2IHom35Y4K3b5dmlQJfjkAL8Q2b/r+YnYJcfF7XTJB6ZA7sQZtWk2Ya5pz47DT9IafJd9myxkuzn/IpzbjipmZk55J41emfEzaLHrFhcORYB8jeSDfsg+fkXazN2ZzsUkRQyrimPZmukfy8yJZSWzDNUt/6zD/tsIbFiJ0M=
  template:
    metadata:
      creationTimestamp: null
      name: oracle-keypair
      namespace: helium

