apiVersion: batch/v1
kind: CronJob
metadata:
  name: entity-invalidator
  namespace: helium
spec:
  schedule: "0 2 * * *"
  concurrencyPolicy: "Forbid"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 10
      ttlSecondsAfterFinished: 86400
      template:
        metadata:
          labels:
            app: 'entity-invalidator'
            security-group: public-rds-access
        spec:
          restartPolicy: OnFailure
          serviceAccountName: public-monitoring-rds-monitoring-user-access
          containers:
          - name: entity-invalidator
            image: public.ecr.aws/v0j6k5v6/entity-invalidator:0.0.8
            imagePullPolicy: IfNotPresent
            env:
              - name: PGHOST
                value: monitoring-rds.cbhihwhsofyu.us-west-2.rds.amazonaws.com
              - name: PGPORT
                value: "5432"
              - name: PGUSER
                value: monitoring
              - name: AWS_REGION
                value: us-west-2
              - name: PGDATABASE
                value: monitoring
              - name: PGSSLMODE
                value: no-verify
              - name: DOMAIN
                value: https://entities.nft.helium.io
              - name: CLOUDFLARE_API_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: cloudflare-secrets
                    key: CLOUDFLARE_API_TOKEN
              - name: CLOUDFLARE_ZONE_ID
                valueFrom:
                  secretKeyRef:
                    name: cloudflare-secrets
                    key: CLOUDFLARE_ZONE_ID