apiVersion: v1
kind: Service
metadata:
  name: geocoder-service
  namespace: helium
  labels:
    app: geocoder-service
spec:
  clusterIP: None
  selector:
    app: geocoder-service
  ports:
    - port: 80
      targetPort: 8000
      name: http
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: geocoder-service
  namespace: helium
spec:
  serviceName: geocoder-service
  replicas: 1
  selector:
    matchLabels:
      app: geocoder-service
  template:
    metadata:
      labels:
        app: geocoder-service
    spec:
      containers:
        - name: geocoder-service
          image: public.ecr.aws/v0j6k5v6/geocoder-service:0.1.5
          ports:
            - containerPort: 8000
              name: http
              protocol: TCP
          volumeMounts:
            - name: photon-data
              mountPath: /data
          resources:
            requests:
              cpu: 200m
              memory: 2Gi
            limits:
              cpu: 400m
              memory: 3Gi
  volumeClaimTemplates:
    - metadata:
        name: photon-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: gp3 # Replace if you have a different class
        resources:
          requests:
            storage: 200Gi
