apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: onboarding-server
  name: onboarding-server
  namespace: helium
spec:
  selector:
    matchLabels:
      app: onboarding-server
  template:
    metadata:
      labels:
        app: onboarding-server
        security-group: rds-access
    spec:
      serviceAccountName: rds-web-user-access
      containers:
        - name: onboarding-server
          image: public.ecr.aws/v0j6k5v6/onboarding-server:0.0.20
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3002
              name: http
              protocol: TCP
          env:
            - name: PGDATABASE
              value: onboarding
            - name: PGHOST
              value: web-rds.cnigyps3bpgz.us-east-1.rds.amazonaws.com
            - name: PGPORT
              value: "5432"
            - name: PGUSER
              value: web
            - name: AWS_REGION
              value: us-west-2
            - name: ENABLE_SOLANA
              value: "true"
            - name: KEYRING
              value: '{"1":"uDiMcWVNTuz//naQ88sOcN+E40CyBRGzGTT7OkoBS6M="}'
            - name: KEYRING_SALT
              value: development_salt
            - name: RATE_LIMIT_MAX
              value: "100"
            - name: IOT_MINT
              valueFrom:
                configMapKeyRef:
                  name: globals
                  key: iot_mint
            - name: HNT_MINT
              valueFrom:
                configMapKeyRef:
                  name: globals
                  key: hnt_mint
            - name: MOBILE_MINT
              valueFrom:
                configMapKeyRef:
                  name: globals
                  key: mobile_mint
            - name: SOLANA_URL
              valueFrom:
                secretKeyRef:
                  name: triton-rpc-url
                  key: secret
            - name: ASSET_API_URL
              valueFrom:
                secretKeyRef:
                  name: triton-rpc-url
                  key: secret
            - name: ECC_VERIFY_ENDPOINT
              value: https://ecc-verifier.web.helium.io/verify
            - name: ECC_VERIFIER
              value: eccSAJM3tq7nQSpQTm8roxv4FPoipCkMsGizW2KBhqZ
          resources:
            requests:
              cpu: 250m
              memory: 500Mi
            limits:
              memory: 750Mi
---
apiVersion: v1
kind: Service
metadata:
  name: onboarding-server
  namespace: helium
spec:
  ports:
    - port: 3002
      protocol: TCP
      targetPort: http
  selector:
    app: onboarding-server
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: onboarding-server
  namespace: helium
  annotations:
    nginx.ingress.kubernetes.io/limit-rps: "1"
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "3"
spec:
  ingressClassName: nginx
  rules:
  - host: onboarding.web.helium.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: onboarding-server
            port:
              number: 3002
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: onboarding-server
  namespace: helium
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: onboarding-server
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75