---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: privy-app-secret
  namespace: helium
spec:
  encryptedData:
    secret: AgCLaD+qNgs+w+6hxzfk+zY3i1qoumnCFuYOH1LIFPeJRcs3Z0qeJ4LAtoe21ZMzP8YOeeNf/UGvpC91ZXFT6hXbFLf9mVXGXf/0gMA4G7cVTiuDFg4PXXDWaQ6noBTN0snTnT9IRujRy3saLOyZsbK2Tt0+hcQWajgKoenbz6qeOLQSSK7rGqWGGK8Bt/KDX7H/bG2gKIc+31HdHJSaPiIABDx1n2VLs05UqsflQzCTTEMcpx5Uq5xwjaW5NvhlBKJmgNdyzK0uDxPHAv76tNwsR19fz2DPMAmfcsSFmmJ2Fzj/qp4OlcA0G5j3DY/+nyBexP1nh7IEYoCVHq8FVmaoB/pf1hH5Y//IVbjLHfC8BGEc2btdNvJhBIhdD8tAsi+zku5pD39QtVzCnfgdVGQEx9VPSP+8NClPvr5qpX0GYJKfI0XZI3jZ4TlLDZP4eC+qTItl8GiSfFHclxh1e/IvfnnoemA37IIyfQuI10rA+ONhKC27G02989mm29AopU2Q0vPb+D8xpR2BgaJywEepkTWb2epuSbBEuORC+cKGlycHVMsN11lrhvaXQkLQLC3YWrrz7cSHrcRSIDQD7iR3uFqbvqzVExY+2Sw1OImPhxTgQzOn3zbPq19DlGFDfcTCBFdhxly94yIgBF+pQ1Is9TKG77eOHDZDmtHPgA2Nw5jySScs5MGRRlZVh9MwCTdyWeHFW+EtaRtCHXk5m3iqkRynkU2mybvxgdzwy69ynNmHs0cxGxHFNhA61mQB9GQ7Erf+hQxMF38y97zUePrGPwBTPKSfeM4mhdPfxXhNy24TZjCAh/Ai
  template:
    metadata:
      creationTimestamp: null
      name: privy-app-secret
      namespace: helium
