---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: migration-whitelist-bypass-password
  namespace: helium
spec:
  encryptedData:
    secret: AgCj+x8oVSwc27tlmSib1xdd3ISIyTVO3X6J6OFJPD75YJemXqWDPl7lKsS7R/IzCbqRM5SBOq7v4Lc4l0EEmkf+268Lyi3uX6BcrP47z0lYHul62eZLOqzOj2//oopCvzeuhZGcYoqjF0oHR2EuviHnXqgY/6LAmeQGBve0/CWjJiQCwVTF8hYqqT+F9U+TkhIppdp3sqIJLjJqKSmkAbn9L+JE/ZHValtNyduK+4y0mUPgvvAUZ11NwAJzvXHrno72VUIhuzNFeo65+2QUnwgOZxOvFDkuai4mwAJR+/88SrPTTD3X494H2n3jiz2MltYCliNcNJ3Cro+W0NiEaGtR0HQrVgNbfLi7OR9T45vmgaCCo/TV2IGoUCv1kFxWzEiLnxboMDCnSiTHzAgD7zu3Q7hOwMaEGBpUqsaYxFb4N/UB6WyVSLFSsvQUkSJeA6pIiPRe10PqOAsJ/3z/cduT5FOfbLB2aKwtdNirKqVIWuWW+24TCjhFvGKzJop58l7/u7byayqnMyJPeyRiOLCPHLZctqfzZRtbNN5FGJJnO1VlUiHJ2ApXRud84zzIgIBGZS+tSxpBL5nadNRjqOziJOWqARYnkbo9XDXNV0QeO9ta+hGyA/vi6GJabpLXoxUivxwu2lXxYORu9YBYvub3ANo71z8f4KroaIlbJSOBXGGvsYpoYmaxpPCUvxQdhhY8W1nyNsAVxoFA/9XiX73f75cx5A==
  template:
    metadata:
      creationTimestamp: null
      name: migration-whitelist-bypass-password
      namespace: helium
