apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: substream-api-key
  namespace: helium
spec:
  encryptedData:
    secret: AgAxumJnmGO8RojaUJu5VtnOHD8m/LhjwMrxVlB6nvcG+PKP63C68n0mQY02a73z0lD+hrSrDlR/18n1R6lNs3lUGM4xxNW39K7tIKsQZNSYNdVi/wOnRK+tawL7Xb1LoMv+JJMdctWylTPzwfxNc+mJfA8BzcIrzHi8ZggJZivpNT8d3CRmVxmEWq+LTLuRgZkPtNyVWgbfkzT1nDlA/+yIbUjgERCxnqP8lT46jLB8vsUbrqfJoX5Dr57KRuCaJprmUCbf8vjfakqgpG/28F3aOE3KvCRtzmBqs2XlAlnTK/BDq4E6v0F1lfDPJ/woc5Hzaq4N2ho4GpJL1zrbyLcBwlsyzvn4QzvJ2uCTthhRQMYHyD04adnpC3iJeAOmXYVgY9Z7Jjh13nIo4VfeVMo5UP1ozH0cXBsA3+WwDbxMhTRk+DAlr0HChMDOkOCzppj1RsOnu40+BUE95aI3xxmYxm2WjLIKMMM9bFXmoOpg3qbT1/+CXO0o7iffX9FUJ3OCQzrr9+Vxrxos3+AgzuEuw9aje4vsmP+Uxdq+sjb3sAL1B33pGGdPbAjJUskQDF6C7945AQEbzYRcr4IhEb97Is77eWaq8+pO2jne9MkBLEMlQ8m/aPC5JqjKzZMz5QASGLOC1xxJDTEUsZ6VCOWgwEUnus7NbfoCx8ZXHSmEWMyvJGDpeofJbhs2zSmQJr6YqLm+j2xi0LQc9wddvTOZi7EGPZvZEzFeFbqP7N7+GmD9Tp6j5Al6
  template:
    metadata:
      creationTimestamp: null
      name: substream-api-key
      namespace: helium