---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: helius-rpc-url
  namespace: helium
spec:
  encryptedData:
    secret: AgAkSEIfNkSXRsx1ycviE/VVOLZ3QEGnwkriCjWdzuLxfBk0UZnfZbgk8D4a00AYZmIPYN/n68Sifpi1tEAniKC+UKYm+TnB+64C4GNLl33+452PdbeK6IvT1i4sPF7rHec7jTw+x0n/VTc/2lZjf1JrvgduVAtBVftkJ0vVAPn/jAqXR7pO5KjFiUV45jb/D7nP/MUPbvjrDrk2FV3TxXF9ijDdhVBtTM6vEF24kg1uP21PP5uz+dMFDo0itE38bWV4TT9fshGDZl6+kSzHLyTAx1zCxsKeD0sBR2cW6s3kmxlrmrMhaOtucCu6LDt3ZsEwW5kx3+hEy+HI0GlJ7yDJlUnjdrGeY5SL7ujrE2K3mcC6w+UuNzboaaqTeqsyeM1sfcrPVnp/+BddkFGKKVyumC2QxlObvJgsY6dTUPIRrgnLCMckijNbRCsnIL+abGwGnMY+1T9taUb1z2TQi4uvBvmGxAOeeuAjci1MttVGF9FIIR0zmW52eEjn68bM0NYvQtX9AfGSVfq9PSkfhQESHBQqAwv5qvHvsbhSd4t90iJbeCdzJb/8HMRpA+lRmMaEGq9814IeiwXPraQaCtnLEtW7BzoBoOAwwgDjOBsgiYDWuRs56wWqWd+iAIgxQr6SFyNCmuzTB+NjvLSA/baDfPFyEp7SsQ0HhG6bcQn8p6ZKcQzalaHtyGSZBZL2PYeIdTEQyoCNqnd5JIW+FG5stRJ7q9Er32TFmm6ghGaNOCeJ3aembvxGlqkQljXNGQ6WcL/bMSR+7oqLPh3pQuA2gkdNmB9XmUp+FjkK
  template:
    metadata:
      name: helius-rpc-url
      namespace: helium
