apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vsr-metadata
  name: vsr-metadata
  namespace: helium
spec:
  selector:
    matchLabels:
      app: vsr-metadata
  template:
    metadata:
      labels:
        app: vsr-metadata
    spec:
      containers:
        - name: vsr-metadata
          image: public.ecr.aws/v0j6k5v6/vsr-metadata-service:0.1.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
              name: http
              protocol: TCP
          env:
            - name: SOLANA_URL
              valueFrom:
                secretKeyRef:
                  name: triton-rpc-url
                  key: secret
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8081
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 400m
              memory: 750Mi
            limits:
              cpu: 800m
              memory: 1000Mi
---
apiVersion: v1
kind: Service
metadata:
  name: vsr-metadata
  namespace: helium
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: http
  selector:
    app: vsr-metadata
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vsr-metadata
  namespace: helium
  annotations:
    nginx.ingress.kubernetes.io/limit-rps: "10"
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "10"
spec:
  ingressClassName: nginx
  rules:
    - host: positions.nft.helium.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vsr-metadata
                port:
                  number: 8081
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: vsr-metadata
  namespace: helium
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vsr-metadata
  minReplicas: 2
  maxReplicas: 7
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
