apiVersion: batch/v1
kind: CronJob
metadata:
  name: close-governance
  namespace: helium
spec:
  schedule: "0 */4 * * *"
  concurrencyPolicy: "Forbid"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        metadata:
          labels:
            app: 'close-governance'
        spec:
          restartPolicy: OnFailure
          containers:
          - name: close-governance
            image: public.ecr.aws/v0j6k5v6/crons:0.0.8
            imagePullPolicy: IfNotPresent
            command: ["node", "/usr/src/app/lib/src/close-governance.js"]
            env:
              - name: ANCHOR_WALLET
                value: /usr/src/app/keys/keypair.json
              - name: SOLANA_URL
                valueFrom:
                  configMapKeyRef:
                    name: globals
                    key: solana_url

            volumeMounts:
              - name: cron-keypair
                mountPath: /usr/src/app/keys
                readOnly: true
          volumes:
            - name: cron-keypair
              secret:
                secretName: cron-keypair
                items:
                  - key: keypair.json
                    path: keypair.json
