apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: helius-service
  name: helius-service
  namespace: helium
spec:
  selector:
    matchLabels:
      app: helius-service
  template:
    metadata:
      labels:
        app: helius-service
    spec:
      containers:
        - name: helius-service
          image: public.ecr.aws/v0j6k5v6/helius-service:0.0.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          env:
            - name: HELIUS_AUTH_SECRET_FILE
              value: /app/keys/helius_auth.txt
            
          volumeMounts:
            - name: helius-auth-secret
              mountPath: /app/keys
              readOnly: true
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3000
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 250m
              memory: 500Mi
            limits:
              cpu: 500m
              memory: 750Mi
      volumes:
        - name: helius-auth-secret
          secret:
            secretName: helius-auth-secret
            items:
              - key: keypair.json
                path: keypair.json
---
apiVersion: v1
kind: Service
metadata:
  name: helius-service
  namespace: helium
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: http
  selector:
    app: helius-service
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helius-service
  namespace: helium
spec:
  ingressClassName: nginx
  rules:
  - host: helius-service.web.test-helium.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: helius-service
            port:
              number: 3000
