apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: helius-auth-secret
  namespace: helium
spec:
  encryptedData:
    secret: AgCMK24YleS1Mqzmv4KE77AqaESTfwt1r42VTrzMgVgFb3DOXhwXCM2MZY+5d2a3QbB/TPDQLhGX3J43AE8AmRqcOkwC9uOeaeWMb2da3A+qCw5LbxBgpEjEJKr59RAc7fuz+GG9SXm1gqqsEMHeimQQjZv3OPgtyzMzLO3+YZGGePBSHp6cYZjNLkA8qN3TQcGgtYvePx95tybwz46YrMVpRZWpPuXvMYsuwqKjYhHqxJQRUE83ZQmxOn/MKxVClZyIOAXCm2nSlZgGaCS/7S9mPvtbyFwFEJkVLji98iusBS9WRCQIqlD+J/hFJ1iJNgOJkyQav0cKTHDek8hTy97omCaBMwUnEwZP6HytdlKPFS0/FZXesSlRYbMbSnZRh+rEOm85aAXF5nZ5UfF8r5dj0lDOGTf7njSbgCaUW5ay5IdvDu8NS6m6VLmYjXkIovG5sv7bmNcHduamJCUSjm2y9GGhxONwEP/lozHZUXx620qbFulaXUCWwY4nBx5yLImYfNEI8Dz8e4Zp0CXdtqJXnXdfaXgds2G1YSBWnzOF2ulOj/2XUfCHHS3jUKRTSxIWQjAntFF377tJZ9ywEjMShClqg9OCT1eQNTN3mXzeOCrfStCxItdDdmp5B1vPxbpBd2SWHaT1GwUbMMvSwM5bkyVMQW22NnNdhomArs2pWiA21PG4jfgB7kfLKBk3ZLp2FJouCfQ6c1gXlBhf
  template:
    metadata:
      creationTimestamp: null
      name: helius-auth-secret
      namespace: helium

