apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: migration-service
  name: migration-service
  namespace: helium
spec:
  selector:
    matchLabels:
      app: migration-service
  replicas: 1
  template:
    metadata:
      labels:
        app: migration-service
        security-group: rds-access
    spec:
      serviceAccountName: rds-web-user-access
      containers:
        - name: migration-service
          image: public.ecr.aws/v0j6k5v6/migration-service:0.0.12
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
              name: http
              protocol: TCP
          env:
            - name: NAME
              value: devnethelium5
            - name: NODE_ENV
              value: staging
            - name: PGHOST
              value: web-rds.cnigyps3bpgz.us-east-1.rds.amazonaws.com
            - name: PGPORT
              value: "5432"
            - name: PGUSER
              value: web
            - name: AWS_REGION
              value: us-east-1
            - name: PGDATABASE
              value: migration
            - name: PGSSLMODE
              value: no-verify
            - name: SOLANA_URL
              valueFrom:
                configMapKeyRef:
                  name: globals
                  key: solana_url
            - name: ASSET_API_URL
              valueFrom:
                configMapKeyRef:
                  name: globals
                  key: asset_api_url
            - name: ANCHOR_WALLET
              value: /usr/src/app/keys/keypair.json
          volumeMounts:
            - name: migration-service-keypair
              mountPath: /usr/src/app/keys
              readOnly: true                  
          resources:
            requests:
              cpu: 250m
              memory: 500Mi
            limits:
              memory: 750Mi
      volumes:
        - name: migration-service-keypair
          secret:
            secretName: migration-service-keypair
            items:
              - key: keypair.json
                path: keypair.json
---
apiVersion: v1
kind: Service
metadata:
  name: migration-service
  namespace: helium
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: http
  selector:
    app: migration-service
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: migration-service
  namespace: helium
spec:
  ingressClassName: nginx
  rules:
  - host: migration.web.test-helium.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: migration-service
            port:
              number: 8081
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: migration-service
  namespace: helium
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: migration-service
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75