apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: faucet-keypair
  namespace: helium
spec:
  encryptedData:
    keypair.json: AgAC3HiXYEDnJsecO4K5JFClqQ89Yevve+MCZTx9oGyZ1eNiUnsbSQ1WCd9/StoBhz+N4qhPH0HVHX5EkMqfwlGrONfLuZGNJSFuUA94dNMFkzhjxBY+cDrGcRUytOhYh60ql4ZbpKxjRaxYn/ogbEfaL5jfwzUQKiBBZS6rH44tFKDhoplNXc28R2RmZzk7l2eiieOvjAGRq3VFHINwBkYN9AJqXUQfbTZpE3DGr/3iIMDa+PSz4h2Sg9uuiVRfzd67CjsZobkU8LN9A1uli5WBqnHPL56cGjxLUnZJEKpCyTpG95E2dTQu3sw/o8xlrGi14oOyw9f31uQhtdXU1e02YLw5xf/W7i4GSRmMal2rNXF7ySNrySyGfeCbP8HnpxJpsMGh5nMXl0or+wKjj7Ebf6EuuPKYWgjPzkpEPcuxyPWkEpi4Vasp1MUv12wwZptOmB5TD+O8zAlGOuRuoMgmKNO2OosjE9i96w68Cv3dfM2AmQ4CmCyTlTwuoC9598TuvJNx09BYPaZ5VKoJzSIoCA3hNEmv1v9O2N2dehZJpmbdKxrQKLvhSJUohJDZDaA9KyQrBfjVuStj7kWRVMmit6wC2XUOMhtdi6564cPjNx9DH4wiQs7NqvaQ7vU37v69J572mvuD9FpW3dP50CKDuacxyI5Xuy2PuQwwyTDozq9kphR37LOODLdn4AniMpOW7DA1X0WaJXUPo3/Lg1pcxbyVjICh8onOy4JbtLH/82xDoeINcc2/2PxZ1AvhCzmYDiEBaTjIif+fFXprU/ENCwH7Lb8OD9EqHlVqlxLc5Gh0AgANZUmWuKwACQVw2sGZQkc3apyHeVVGaDrhR8ZCXuAW6PhtaoHE6THRwMRaqfws/Azpgv4CD7QDlmmI4Uf5edswZsc2dQJZStryDHXWCY2F42T1Yw7RquuBMejbhOdlX1Tlre85gsHiICR67QUlx1BMMjC1GXqrB47YDZstu+8Kee45jBUFEVHoyYd0Bg6s3+DirHa1
  template:
    metadata:
      creationTimestamp: null
      name: faucet-keypair
      namespace: helium

