apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: helius-auth-secret
  namespace: helium
spec:
  encryptedData:
    secret: AgB9fZEH3tVjdU93BmZQ8b3Bnkf08ZiYigx1klbGyTSVRmSChoQEo6elahcejdc6yHnUOEhNHBVeuRQUbF6/kEO1sSfgapeXSC+A8Evwc2D+lJeVZ+5/BdE7oAhGh9jMY7hD7YcTOFa8f8bwNYLabecq5EeVPZljrBTNOS3N9rrsKgkK9Gho6bhc8ZXQCs64CpaGPk//Xd2x1FSFyOzCFiJC1tM5REd1k21WwG+z5OAZtd68ODT4D5o9ZdhA15wdnxsmCQy/dj/LZAmDlVgdHXWNmYJfBBCESnSt4z34euo2kFJ5vHoLKfMpXfFpf1r6zR4QAl8z25frlctqsS80CFDj/okO1wRlY++KovDB2tAxXnCH102VBjIqwWvRNWCMSzszc2YnrtxC+jhXVcniPinDyIqA7bSRpw2RoZaTaXpU8bOfYUXbJSKTivSpX36lL7HMtsYtGqsSZXLuKhvb0mKt6qiBxYYoihookmBPJZZwcZmW1NVKuFqyWMH8qQpobBZ4RoUyt0WBgvYW7bf6SbidXQjgt82EP+JZnxht2YwsoMxn1xhJaE8NJrDWMcSKYv/uoT0kSJZWNYrfXGfmUcHF2nmqKHT5wHyItbZoxcHehCeuDyUu95XI97DO0mwJdeS2YA+sTMpd6ED5Z8utwI6hAPDTJgYXrO7ZqkxBGZO6a2aXNSyKeX3y4hkTIEMg5Jq+oyC0MnLg91ZGkRAk
  template:
    metadata:
      creationTimestamp: null
      name: helius-auth-secret
      namespace: helium

