apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-secrets
  namespace: helium
spec:
  encryptedData:
    CLOUDFLARE_API_TOKEN: AgBxhztiOv0jv2RE9SLkU/gQ+BMvzSZXdFNrssmBwYI4mq1gXQhKsTSmXLu3kjCSKuEtU0Pg5/D0wfOcwMGgsjVRcq7cX4KkZd4sohdOGmiZ0YoLXZSlO1K9JM3Y0z8oXbl48p2/wceEDj+fdT1aXujtk/Jm3eNdxAKn/N9mZnC9FNLrTPrVkah2vv5+dvL7BwCcdvXQ4gvMPZwcKpRoIdWs1VUL04Pc4hHtjAf2Q5E+El5CriDvCJnF3NMkYE+CP8NkV1Y0XhsN4dfvQb5Z9/Z0mAkQsY+AJSt+6vzzV79ff8iQMu5cQihHTSQ0uAbmMwj20VLBi6ol9JuZ4HABoJCgIlgNeXLTKDnY+alUmmU6wo1ABDRZBm8S/UElXJmO/aIXDLp0DyVR2vJ4v+XDllIF1mAAljulZJu1If1kqf9CsR4DwyQmv758KuGnC0MSMgyYA5ZpqWIl484HxbNMvV2eUlztFlcSKdd9Sh4S328dNRtzjsvoXAiTTYqlUKQVjd1PHC5vgS5mpCqmqTxxjC6aPd7VuNcBgQt7cMVtta/3LUtcWc1sZhr18uOsaxEfuOrr56yx684N2OFyK+7HJrW8dA01eln0hkYcLfFh+6HIJI9IBdeYNYp/OyiLSwi2jM8fOoCyM2uZ5oVWIy4DW7MIZfu7kSVe13w4C3Jo4YktJ9mbKASk+ojJdQu8HQSt65dL2YOvno3ukuVHY1zpt4+6wspCurN8Ld+ElXzIo7np/nkiKFXrz20D
    CLOUDFLARE_ZONE_ID: AgAyCFVIpQnay0CvZ/gi3VIEn9wXKGqyUlqCrvG1v1dwDdyR0R8ArXSCaT5J1qDkc1e/niBAGKLITKcu382eZhHoSBQdGV5ybUaoCGgsAg+PiOoHAJ/SQHquT/m3A7D4AqdSXQeRbpsYlOjGC1UIEGns/On1ftMfnEdxEW/1bq6Gu6a1/i3M4eERmVo6tHg3wXaM0GrMD43qD3s5LtF1TQ/8hFKmdktVN9eLTkJUmnU/1/QhqDWVUBDGBFs5ezoQoUBZzzvl8lCuMpi1TghrJs1ettgYvPJfkl3TQkJfXS9+ywN9gljCHF/qy8U4C+sI69x8Ywoa5hK7pKiRwFnaLBOYmwtMnQ0xy/thYJuVdpLh4Rfd8i+GAESsZP1e4W0vTHnOyk3CmzDt2D45gaYwwHOwo26f6KywiNKLgyVYoLKjMcohRlLFkSw5KN5dtBpXqhmJVJpxJM48s2jSZHKEllNKHFhAcu2tcvI6Bk6D0ksXHce8asTjQV+tWYUqbTiCAiQQaRdo7KWIG+CD7rIaz+ogLi26lU9pfUTPNxk2kJu+y5IWo3867JkEonxNao5LqLK7rpUxVVGeoEvfIrv65Je9nYYt5cp1ZPT+9QTMhikd5pjpkGGj1lWclX5tyKcg7xKgtzY6Z/6ZMYr0VKOxPcK7Jzy/4IPi+WnJLe5eNVUrZt06mhN23pA8csmc631yPtprN53ofH7LpKjnhyheyKX7LFdhUwMuE8cYa0rCfpYPgA==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-secrets
      namespace: helium
    type: Opaque