---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: privy-app-id
  namespace: helium
spec:
  encryptedData:
    app-id: AgAjUVpHRPYdsFTas+PyiJXjkh6aSN0aJzHqeX5VLBOase4Dj28QzdvPkBTazgIkmYevKLBe2z6wCFzd1izOkC7N6ReMaRIEVUVGfVQ6Nh6uUeIpYI65AAj7tGLOm3xvkV0n8pJuAjsd75h83CKPMeqKJKyzHhmgzVQxc9a59jShJRnkTbb0AnR0uffpGpqXFdblo4UsrNoQIo8a+Z9veq11U8rJJqVfVG0T5CgG1fSARlRTaYxp7jx1ABDIz6kpxR8YtYHSZ+Mm9zGnm9aSkEXowH9YWsBYIhDTJ9id0q6AJgp3TNU3Ty5krI/8X8J5LDnzuwb/yg8XO8eBtT+xSnulhuw8ffMRAqUNoe59AIfDtehGyXnk+ojRVOt9+EOKWHWlqPQ3uDwhj9u9MpncNumhS4kcD/rxEwSaJl2ALr+zu/mjOu3JvPCEPX55g2/v2od1F4EdoNUgcCSO9ZOpsr/ro/qjInpn+ce9LSu5fwb3nrUg/2h3LmQx0YOEry+M7VerNuFCJCS7eNDVv5OO1UjaTBlZxI2BSZlOgFH/wGxY1E2LUGVyOQNActEWg8gWNwfQsOPwfH/bd+DdMMALzKLwTq4jLSz24jsc2P1uh/zVObMyzAFlTlgx+PofFRqKvZpshlL37oA8ZpMwQndf9OVyM8+DMscjVDt0tLvLNPRBJYXNKEHMRxwzPKkOr0XlJGyE8fRDGcDXPBhKSIX9cSskh6261U5xnnuz
  template:
    metadata:
      creationTimestamp: null
      name: privy-app-id
      namespace: helium
