---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: migration-whitelist-bypass-password
  namespace: helium
spec:
  encryptedData:
    secret: AgCJ3M0t5dep3gSlQZWlsaH1BQ0Nr3n1/DsbHAsml7NcKyc4GF1NimzGtYdw4bmCAZdhE23dTr2JnMG1hQpeWagIsCWNkxLb2VJcR93vn7foEmqmyxXR6u6ghWupNhZ9uOsXq5ezcGI5xlTTanyLF4nOnINWHe7/xT00HxyhCfTjCsX+kYQa/9RQvMCKC8NJ9g3Q8I3vsQt0nkn7ARtSyPAvEPl3eNV2AQ2BpTygUVrK52bZbB97sOBPugHEvsjCpN3u08X5Rh3T7TJePI4itXuDxWBpnh4i48OKvePaxTNogr7AKzFmK2/IaPgiUNIdvKqiAhOgLOuPYcLTQXXf5Lf/dT9qhmPtOMOQs0yn6fw7OkirMjqJ9EoYTtvDRC9XMYhLyCHwIPVl5Nk/ayzNUKaYjdGQjIa9kdrEpadIGDP2Wcj2K9y4xNaXfk0UxbjINY8JwHn1G/Sh8caeo6E42bNF3k+QW8uIc0EG4OiFeP7FFB9JlcRnbrsmZuFTTCwD9NNZA1IyaADEwe3sqB43hJrHNUtEB/xd0N/aueo5HrI3DNjX4B6yBDUYniSwinJKJuGm3N18aBqsjsnEdiT2nyrjt5XYuv01dk2xigCPzno0fTlBzMM6KL8OAPMxXbamM/eu4P8Cje79ehCrBCNm5OmfLGNAPnOwhszYhWmRR2HNBdKnVTV35lla5TGh34orDZtSPbvhJ/dZrDXVPGB1T2JBBb/zdw==
  template:
    metadata:
      creationTimestamp: null
      name: migration-whitelist-bypass-password
      namespace: helium
