---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: migration-whitelist-bypass-password
  namespace: helium
spec:
  encryptedData:
    secret: AgB5OLeJM5xBApcMSktkL+z+vlp9VZz8Q6EguB1aPnp0XszGhAKB5jfSgld8BQkROt+X41xewarTAVHZCvzKhrXCJKOYg9iI8Z0EgE7FKsYURDmB6TgLBMyG/+vILG3ol+fRRG1QQyxZt4qkGw7v9F8/hx+R2GTqq9AojPCr1Y2V8Rm6m4igAiSCBrsxyu39e4YUYEEPKfPTu2AERGDp0wjE95kNoPBeFc1uzC89Vx0hG2cAVxiCBDeUkp8meIL/qC/vEf1OoJ1g5NhSR/zRVaPGaqg1nq85it2ACRTiOwXa0qPH/QPSB1ZVAs7DxeAZj8+4JBzu3S7nwDjR6JqYYgRnWFzQjscgMXpbtpqiFEtPcnFaq0ZnvGh5X9AYYsDQK4lDPOAsupmunuGF6kYOkq9jFro8tCPlXBtNOl+otwOzEImqoW38OLCC4AvUUiYGip265u9haEYCTADRVaMt2MnvYgd5PxbWHLO9ozusS2KdFuCOgAVc0oYFv7MKIvQYBU8TSNv70yiT+cLvxPAzb/CvwnLtZYRj3bI3bvK6KnX1nl0arM8ykcxRjD/B6yt7MiWq7DbsW53fGenr9N5SvhSXQpGb4TwOI+HOPRz4UhiQ+SvMe9TqKU9r6xzSshFYwtcmVsZpPgonabe/5QWS/L8iB/eYjb4uRMtsRfwkkPqKge3M21nEvfWeiCb69654SrUvXEkjJFxQg7GnbKHLBOqDJkTHDg==
  template:
    metadata:
      creationTimestamp: null
      name: migration-whitelist-bypass-password
      namespace: helium
