apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cron-keypair
  namespace: helium
spec:
  encryptedData:
    keypair.json: AgAq9x5HwIq8nVodIni0zCE5U8q+meQ1setjXNs4X9ntkOuN+TX/TfzWbYCmG+srrwjTWyFTeRQ8vEpgvGoT9gcD7xz7sf5jhGGv4ptv4orkE+FZGnAanIhUTESdHiNWGvn7aC7QJ8W6TNCETLWKaBTqunw7GY2dbouS9amGUBfNEOazbjyXWQZtmNM5BKKz18mczyN9g3+0D1ImzflUeOcXlAm3GHpbI9WFRQQIu8x4pdEjcIBWVWP02axVCBb7o6tRtw+5DpsxM5TEJlNcdCA+TKtUnAjyvVOfBMqiRNAyCALlDRtb3a7HOe0fX819AHuvYbQQY1QWrfJ11C7dPf39SYG0dJq9AyWJn3f2RXQ8GkVG9hgN8yV0S0ewThcP6RrXidYLVSXsf1GXmwxA7AioTfvQ1xjvEWeXfx7r8U/XXFTF3Ni3zfC4zHoP8iUgJUzgTcivZ1IMMTv/bpA1kO4GZ7I9KIG/elaR0+DA4Tv2jdFRp8WtmZLLWeOljkLy6dNyVf1mTdrJOROT+VR56RAg/VI7Bp9C6orOqGiNwjKkodXPyB+UurTvXeWahGwoKOrWlbGtrx/lm904q9pO4M0gQHzLfnj0jlORlT7A1prTwajFXgc/Pw/k34WuAB6N49zmWurW8SFuO1ees2u7EV1w99sggXA0Bj/kPGMVFu/aFh9ppy9zxz+5d9LkIRWs2b8FDYeiH9nFTQz9ft8+TynrUA+DYLGzLbNXiZp2WEB9wNvWYh35szErhaYuuf/ECkVrfwRHUkBXEHbZTpRmBHyyDaOaaQYpTRhtsmhZ1t6Q5QpvCjfSNaUWhEUR9Pvn72yfhilBlHxsHoaDDOqq9UvbbI++Ve+ebj7AuusT5TDFUkLUF+XUOk7WcqB7lOVJaBk///1tCGpBfBqT2nNgap0YPSjjc5KwWnzr/GiJPiGTYxETmMsdZiI0E5ZKPRgc/GfueKadsfViNA900WLYxcEcQinL616dtg==
  template:
    metadata:
      creationTimestamp: null
      name: cron-keypair
      namespace: helium

