apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tuktuk-crank-turner
  name: tuktuk-crank-turner
  namespace: helium
spec:
  selector:
    matchLabels:
      app: tuktuk-crank-turner
  template:
    metadata:
      labels:
        app: tuktuk-crank-turner
    spec:
      containers:
        - name: tuktuk-crank-turner
          image: public.ecr.aws/v0j6k5v6/tuktuk-crank-turner:0.0.1
          imagePullPolicy: IfNotPresent
          env:
            - name: TUKTUK_RPC_URL
              valueFrom:
                secretKeyRef:
                  name: helius-rpc-url
                  key: secret
            - name: TUKTUK_MAX_RETRIES
              value: "5"
            - name: TUKTUK_MIN_CRANK_FEE
              value: "10000"
            - name: TUKTUK_LOG
              value: "info"
            - name: TUKTUK_KEY_PATH
              value: "/app/keys/keypair.json"
          volumeMounts:
            - name: cron-keypair
              mountPath: /app/keys
              readOnly: true
          resources:
            requests:
              cpu: 250m
              memory: 500Mi
            limits:
              cpu: 750m
              memory: 750Mi
      volumes:
        - name: cron-keypair
          secret:
            secretName: cron-keypair
            items:
              - key: keypair.json
                path: keypair.json
