name: Invalidate Cloudflare Cache for Web SDLC

on:
  push:
    branches:
      - develop
    paths:
      - 'manifests/web-cluster/sdlc/helium/metadata.yaml'

jobs:
  purge-cloudflare-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Purge Cloudflare Cache for Web SDLC
        run: |
          ZONE_ID="${{ secrets.WEB_SDLC_CLOUDFLARE_ZONE_ID }}"
          EMAIL="${{ secrets.WEB_SDLC_CLOUDFLARE_EMAIL }}"
          API_KEY="${{ secrets.WEB_SDLC_CLOUDFLARE_API_KEY }}"
          ENDPOINT="https://api.cloudflare.com/client/v4/zones/$ZONE_ID/purge_cache"

          DATA='{"purge_everything":true}'

          response=$(curl -X POST "$ENDPOINT" \
            -H "X-Auth-Email: $EMAIL" \
            -H "X-Auth-Key: $API_KEY" \
            -H "Content-Type: application/json" \
            --data "$DATA")

          echo "Response: $response"
