name: Invalidate CloudFront Distribution

on:
  push:
    paths:
      - 'manifests/web-cluster/sdlc/helium/metadata.yaml'

jobs:
  cloudfront-invalidation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Invalidate CloudFront distribution
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Create CloudFront Invalidation
      run: |
        DISTRIBUTION_ID="YOUR_CLOUDFRONT_DISTRIBUTION_ID" # Replace with your distribution ID
        PATHS_TO_INVALIDATE="/*"       # Replace with paths you want to invalidate

        aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths $PATHS_TO_INVALIDATE
